language: C
dist: trusty

sudo: required

script:
  - rm -rf *.log *zImage* gcc
  - chmod +x b.sh
  - bash b.sh
  
  after_success:
  - cp arch/arm/boot/Image.gz-dtb gionee-zImage

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file_glob: true
  file: gionee-zImage*
  on:
    tags: true
    repo: Unofficial-kernel/kernel_GBL7360A
    branch: master
